views:
  - name: mt_line_items_view
    description: "Data about individual line items (products) sold"

    cubes:
      - join_path: line_items
        includes:
          - created_at
          - count
          - total_amount

      - join_path: line_items.products
        includes:
          - product_category

      - join_path: line_items.orders.users
        prefix: true
        includes: 
          - city
          - age
          - state
          