views:
  - name: orders_view
    description: "Data about orders, amount, count and breakdown by status, users and products dimension."
    meta:      
      folders:
        - name: "Folder A"
          members:
            - total_amount
            - average_order_value
        - name: "Folder B"
          members:
            - completed_count
            - completed_percentage

    cubes:
      - join_path: orders
        includes:
          - status
          - created_at
          - id
          - created_at_Year
          - created_at_Quarter
          - created_at_Month
          - created_at_Day

          - completed_count
          - count
          - total_amount
          - average_order_value
          - completed_percentage

      - join_path: orders.users
        prefix: true
        includes: 
          - id
          - city
          - age
          - gender
          - last_name

      - join_path: orders.line_items.products
        prefix: true
        includes: 
          - product_category