views:
  - name: orders_view
    description: "Data about orders, amount, count and breakdown by status, users and products dimension."
    meta:
      hierarchies:
        - name: "Demo Hierarchy"
          levels:
            - users_city
            - status

        - name: "Created At Hierarchy"
          levels:
            - created_at_year
            - created_at_quarter
            - created_at_month
            - created_at_day

    cubes:
      - join_path: orders
        includes:
          - status
          - created_at
          - id
          - created_at_year
          - created_at_quarter
          - created_at_month
          - created_at_day

          - completed_count
          - count
          - total_amount
          - average_order_value

      - join_path: orders.users
        prefix: true
        includes: 
          - id
          - city
          - age
          - gender
          - last_name
          - count

      - join_path: orders.line_items.products
        prefix: true
        includes: 
          - product_category
          - count