cubes:
  - name: products
    sql_table: ECOM.PRODUCTS
    public: false

    dimensions:
      - name: id
        sql: ID
        type: number
        primary_key: true

      - name: category
        description: "Product category"
        sql: PRODUCT_CATEGORY
        type: string

      - name: name
        description: "Product name"
        sql: NAME
        type: string

      - name: created_at
        description: "Timestamp of product creation"
        sql: CREATED_AT
        type: time

    measures:
      - name: count
        description: "Product count"
        type: count

