views:
  - name: orders_view

    cubes:
      - join_path: orders
        includes:
          - status
          - created_date
          - count
          - total_amount
          - average_order_value
          - total_amount_shipped

      - join_path: orders.users
        prefix: true
        includes: 
          - city