views:
  - name: order_info
    description: "This view contains information about orders, the products in those orders, and the users that placed them."

    cubes:
      - join_path: orders
        includes:
          - status
          - created_at
          - completed_at
          - days_to_complete

          - count
          - completed_count
          - completed_percentage
          - avg_days_to_complete
          - total_amount

      - join_path: orders.users
        prefix: true
        includes: 
          - city
          - age
          - gender

      - join_path: orders.line_items.products
        prefix: true
        includes: 
          - category
          - name

