views:
  - name: order_info

    cubes:
      - join_path: orders
        includes:
          - status
          - created_at
          - completed_at
          - days_to_complete
          - count
          - completed_count
          - completed_percentage
          - avg_days_to_complete

      - join_path: orders.users
        prefix: true
        includes: 
          - id
          - city
          - age
          - gender
          - user_count
          - last_name

      - join_path: orders.products
        prefix: true
        includes: 
          - product_category

          

